### ISSUE TITLE
how can i get the graph system enabled?

### ISSUE THREAD

**Issue by allaze-eroler** [infinity8/StructuredXmlEditor#6]
I'm having an hard time figuring how to get that graph system I saw on this page: https://github.com/infinity8/StructuredXmlEditor/wiki/Graph The explanation is TOO vague it also lack of step by step pictures... All I see is just an example which didn't give any hint at all!

**Comment by Lyeeedar** [comment]
So to use the graph system create a new document with a GraphStructDef or a GraphCollectionDef as the root node (instead of using StructDef or CollectionDef as you would for a normal document). When you create one of these documents it should automatically show the graph edit view.

Anytime you want to link to a new node use a GraphReference (instead of a basic Reference). You can only put GraphStruct or GraphCollection items in a GraphReference. In the graph edit view this will show as the node like, and have an option to create a new node.

Hope that helps more. If you link the definition you made I can take a look at what you are trying to do an suggest things to make it work.
